### ISSUE TITLE
3.12 support?

### ISSUE THREAD

**Issue by joshp23** [addiks/gedit-dbgp-plugin#7]
I might be missing something, but there is no appearance of "Debugging" in the menu under gedit 3.12.2

is this a known limitation or is this pebkac?

**Comment by addiks** [comment]
If the "Debugging" menu is not there and you have actually activated the plugin (please make sure), then this is something i would not expect. However as of now i cannot say if that is a incompatibility with 3.12 or some other bug. I am using it with 3.10, where it works. I will now try to get 3.12 working on my computer to have a better look at this.

And thank you for your comment! At least now i know that someone is actually using the stuff i put on github. :)

**Comment by addiks** [comment]
Can you tell me on which distribution you are trying this (With version-numbers etc)? Looks like i will run into a big depency-mess trying to get 3.12 running on my machine. It will probably be easier to try this in a VM using your distro.

**Comment by joshp23** [comment]
Hey. Glad to comment, I get it :) Every time someone stars one of my repos, I have a quiet little pizza party. 

I'm using Ubuntu 14.04, and running an updated gnome shell by adding these repos

`sudo add-apt-repository ppa:gnome3-team/gnome3-staging` 
`sudo add-apt-repository ppa:gnome3-team/gnome3`

according to [these simple instructions](http://www.webupd8.org/2014/05/how-to-install-gnome-312-in-ubuntu.html)

**Comment by addiks** [comment]
Update: I now got 3.12 working in a VM and can confirm it not working there. It seems that the UI (including the menu) was massively revamped in that version. I fiddled around a bit with it but could not get it working (I also tried the [patched version](https://github.com/JacekPliszka/gedit-dbgp-plugin) which was marked as a fix for 3.14, but it seems to do nothing for 3.12). I will however continue to work on it because i myself want to upgrade at some point.

**Comment by joshp23** [comment]
good eye on that 3.14 patch. 

not so sure I like the 3.12 menu revamp. in my decrepitude, I have grown resistant to change...

**Comment by addiks** [comment]
I've finally got the menu visible and kind of usable. You can test my current WIP version in branch "gedit-3.12", i had not yet time to test it fully. Currently it seems that breakpoints cannot be set, which i will be working on when i get back to it, but there may be more issues.

The whole menu-code had to be re-done and implemented twice (old and new) to get it work in both 3.12 and 3.10.

**Comment by joshp23** [comment]
hey!

you, sir, are a hero of the realm. My computer died from a rolling power outage, so I bought a new one and loaded it up with gnome 18 since I no longer had to be concerned about upgrading ;)

ciest la vi

**Comment by addiks** [comment]
I have now got actual debugging to work in 3.12. Turned out that setting a breakpoint did not work because i had no file open, sometimes i am just stupid. Had to fix one other small bug to get debugging working.

I don't know if this is still relevant to you on gnome 18, but maybe you want to test/use it.

**Comment by addiks** [comment]
After not hearing back for a few months, i think this can be closed. If you disagree, please report your current problem and i reopen the issue.
